# Generated by Django 6.0.3 on 2026-04-01 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_account_options_alter_budget_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('resource_type', models.CharField(blank=True, max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('raw_text', models.TextField(blank=True)),
                ('merchant_name', models.CharField(blank=True, max_length=120)),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_scans', to='transactions.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('valid_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-valid_at', 'base_currency', 'quote_currency'],
                'unique_together': {('base_currency', 'quote_currency', 'valid_at')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('budget_alert', 'Budget alert'), ('low_balance', 'Low balance'), ('large_transaction', 'Large transaction'), ('goal_milestone', 'Goal milestone'), ('sync', 'Sync'), ('security', 'Security'), ('payment', 'Payment')], default='sync', max_length=30)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email'), ('push', 'Push')], default='in_app', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payee_name', models.CharField(max_length=120)),
                ('payee_reference', models.CharField(blank=True, max_length=120)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='transactions.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('asset_class', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('crypto', 'Crypto'), ('bond', 'Bond'), ('cash', 'Cash')], default='stock', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='transactions.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['symbol', 'id'],
                'unique_together': {('user', 'account', 'symbol')},
            },
        ),
    ]
