# Generated by Django 6.0.3 on 2026-04-02 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_role_defaults(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("users", "UserProfile")
    SystemSetting = apps.get_model("users", "SystemSetting")

    UserProfile.objects.filter(user__is_superuser=True).update(role="administrator")
    SystemSetting.objects.get_or_create(
        pk=1,
        defaults={
            "site_name": "Personal Finance Manager",
            "allow_self_registration": True,
            "default_base_currency": "USD",
            "support_email": "",
            "maintenance_mode": False,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('user', 'Normal User'), ('manager', 'Account / Finance Manager')], default='user', max_length=30),
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Personal Finance Manager', max_length=120)),
                ('allow_self_registration', models.BooleanField(default=True)),
                ('default_base_currency', models.CharField(default='USD', max_length=3)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'system settings',
            },
        ),
        migrations.CreateModel(
            name='ManagedUserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manager_assignments', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_user_assignments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['manager__username', 'user__username'],
                'unique_together': {('manager', 'user')},
            },
        ),
        migrations.RunPython(seed_role_defaults, migrations.RunPython.noop),
    ]
